modLoader="javafml"
loaderVersion="[46,)"
license="LGPL"
issueTrackerURL="https://github.com/Viola-Siemens/Random-Crafting/issues"

[[mods]]
modId="randomcrafting"
version="${file.jarVersion}"
displayName="Random Crafting"
logoFile="logo.png"
credits="Liu Dongyu"
authors="Hexagram"
description='''
All recipes are messed up by this mod. You may be able to get a stick from a iron block, or get a netherite ingot from three cobblestones. Can you still beat the game?
'''

[[dependencies.randomcrafting]]
    modId="forge"
    mandatory=true
    versionRange="[46,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.randomcrafting]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20,1.21)"
    ordering="NONE"
    side="BOTH"